# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'caixaMultibanco.ui'
##
## Created by: Qt User Interface Compiler version 6.6.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QLabel, QLineEdit, QPushButton,
    QSizePolicy, QWidget)

class Ui_form_Multibanco(object):
    def setupUi(self, form_Multibanco):
        if not form_Multibanco.objectName():
            form_Multibanco.setObjectName(u"form_Multibanco")
        form_Multibanco.setWindowModality(Qt.NonModal)
        form_Multibanco.setEnabled(True)
        form_Multibanco.resize(800, 660)
        form_Multibanco.setMinimumSize(QSize(800, 660))
        form_Multibanco.setMaximumSize(QSize(800, 660))
        icon = QIcon()
        icon.addFile(u"imagens/multibanco1.png", QSize(), QIcon.Normal, QIcon.Off)
        form_Multibanco.setWindowIcon(icon)
        form_Multibanco.setLayoutDirection(Qt.RightToLeft)
        form_Multibanco.setStyleSheet(u"QWidget {\n"
"	background-color: #B6BBC4;\n"
"}")
        self.label = QLabel(form_Multibanco)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(100, 0, 491, 61))
        font = QFont()
        font.setPointSize(28)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setStyleSheet(u"QLabel\n"
"{\n"
"	color: rgb(255, 255, 255);\n"
"}")
        self.label_2 = QLabel(form_Multibanco)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(390, 410, 201, 20))
        font1 = QFont()
        font1.setPointSize(7)
        self.label_2.setFont(font1)
        self.label_2.setTextFormat(Qt.AutoText)
        self.label_2.setScaledContents(False)
        self.label_3 = QLabel(form_Multibanco)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(630, 50, 141, 21))
        self.label_3.setFont(font1)
        self.label_3.setLayoutDirection(Qt.RightToLeft)
        self.label_3.setScaledContents(False)
        self.label_4 = QLabel(form_Multibanco)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(630, 100, 131, 31))
        self.label_4.setFont(font1)
        self.label_4.setLayoutDirection(Qt.LeftToRight)
        self.label_4.setAutoFillBackground(False)
        self.label_4.setMargin(6)
        self.btnMultibanco_ponto = QPushButton(form_Multibanco)
        self.btnMultibanco_ponto.setObjectName(u"btnMultibanco_ponto")
        self.btnMultibanco_ponto.setGeometry(QRect(240, 590, 31, 31))
        font2 = QFont()
        font2.setPointSize(10)
        font2.setBold(True)
        self.btnMultibanco_ponto.setFont(font2)
        self.btnMultibanco_ponto.setCursor(QCursor(Qt.PointingHandCursor))
        self.btnMultibanco_1 = QPushButton(form_Multibanco)
        self.btnMultibanco_1.setObjectName(u"btnMultibanco_1")
        self.btnMultibanco_1.setGeometry(QRect(240, 550, 31, 31))
        self.btnMultibanco_1.setFont(font2)
        self.btnMultibanco_1.setCursor(QCursor(Qt.PointingHandCursor))
        self.btnMultibanco_4 = QPushButton(form_Multibanco)
        self.btnMultibanco_4.setObjectName(u"btnMultibanco_4")
        self.btnMultibanco_4.setGeometry(QRect(240, 510, 31, 31))
        self.btnMultibanco_4.setFont(font2)
        self.btnMultibanco_4.setCursor(QCursor(Qt.PointingHandCursor))
        self.btnMultibanco_7 = QPushButton(form_Multibanco)
        self.btnMultibanco_7.setObjectName(u"btnMultibanco_7")
        self.btnMultibanco_7.setGeometry(QRect(240, 470, 31, 31))
        self.btnMultibanco_7.setFont(font2)
        self.btnMultibanco_7.setCursor(QCursor(Qt.PointingHandCursor))
        self.btnMultibanco_seta1 = QPushButton(form_Multibanco)
        self.btnMultibanco_seta1.setObjectName(u"btnMultibanco_seta1")
        self.btnMultibanco_seta1.setGeometry(QRect(610, 180, 51, 31))
        self.btnMultibanco_seta1.setCursor(QCursor(Qt.PointingHandCursor))
        icon1 = QIcon()
        icon1.addFile(u"imagens/green_arrowR .png", QSize(), QIcon.Normal, QIcon.Off)
        self.btnMultibanco_seta1.setIcon(icon1)
        self.btnMultibanco_seta1.setIconSize(QSize(30, 24))
        self.btnMultibanco_pagamentos = QPushButton(form_Multibanco)
        self.btnMultibanco_pagamentos.setObjectName(u"btnMultibanco_pagamentos")
        self.btnMultibanco_pagamentos.setGeometry(QRect(30, 360, 51, 31))
        font3 = QFont()
        font3.setPointSize(9)
        font3.setBold(False)
        self.btnMultibanco_pagamentos.setFont(font3)
        self.btnMultibanco_pagamentos.setCursor(QCursor(Qt.PointingHandCursor))
        icon2 = QIcon()
        icon2.addFile(u"imagens/green_arrow.png", QSize(), QIcon.Normal, QIcon.Off)
        self.btnMultibanco_pagamentos.setIcon(icon2)
        self.btnMultibanco_pagamentos.setIconSize(QSize(30, 24))
        self.btnMultibanco_pagamentos.setCheckable(False)
        self.btnMultibanco_pagamentos.setAutoDefault(False)
        self.lineEdit = QLineEdit(form_Multibanco)
        self.lineEdit.setObjectName(u"lineEdit")
        self.lineEdit.setEnabled(False)
        self.lineEdit.setGeometry(QRect(630, 70, 121, 8))
        self.lineEdit_2 = QLineEdit(form_Multibanco)
        self.lineEdit_2.setObjectName(u"lineEdit_2")
        self.lineEdit_2.setEnabled(False)
        self.lineEdit_2.setGeometry(QRect(632, 130, 121, 8))
        self.lineEdit_3 = QLineEdit(form_Multibanco)
        self.lineEdit_3.setObjectName(u"lineEdit_3")
        self.lineEdit_3.setEnabled(False)
        self.lineEdit_3.setGeometry(QRect(392, 430, 201, 16))
        self.btnMultibanco_2 = QPushButton(form_Multibanco)
        self.btnMultibanco_2.setObjectName(u"btnMultibanco_2")
        self.btnMultibanco_2.setGeometry(QRect(280, 550, 31, 31))
        self.btnMultibanco_2.setFont(font2)
        self.btnMultibanco_2.setCursor(QCursor(Qt.PointingHandCursor))
        self.btnMultibanco_0 = QPushButton(form_Multibanco)
        self.btnMultibanco_0.setObjectName(u"btnMultibanco_0")
        self.btnMultibanco_0.setGeometry(QRect(280, 590, 31, 31))
        self.btnMultibanco_0.setFont(font2)
        self.btnMultibanco_0.setCursor(QCursor(Qt.PointingHandCursor))
        self.btnMultibanco_8 = QPushButton(form_Multibanco)
        self.btnMultibanco_8.setObjectName(u"btnMultibanco_8")
        self.btnMultibanco_8.setGeometry(QRect(280, 470, 31, 31))
        self.btnMultibanco_8.setFont(font2)
        self.btnMultibanco_8.setCursor(QCursor(Qt.PointingHandCursor))
        self.btnMultibanco_5 = QPushButton(form_Multibanco)
        self.btnMultibanco_5.setObjectName(u"btnMultibanco_5")
        self.btnMultibanco_5.setGeometry(QRect(280, 510, 31, 31))
        self.btnMultibanco_5.setFont(font2)
        self.btnMultibanco_5.setCursor(QCursor(Qt.PointingHandCursor))
        self.btnMultibanco_3 = QPushButton(form_Multibanco)
        self.btnMultibanco_3.setObjectName(u"btnMultibanco_3")
        self.btnMultibanco_3.setGeometry(QRect(320, 550, 31, 31))
        self.btnMultibanco_3.setFont(font2)
        self.btnMultibanco_3.setCursor(QCursor(Qt.PointingHandCursor))
        self.btnMultibanco_00 = QPushButton(form_Multibanco)
        self.btnMultibanco_00.setObjectName(u"btnMultibanco_00")
        self.btnMultibanco_00.setGeometry(QRect(320, 590, 31, 31))
        self.btnMultibanco_00.setFont(font2)
        self.btnMultibanco_00.setCursor(QCursor(Qt.PointingHandCursor))
        self.btnMultibanco_9 = QPushButton(form_Multibanco)
        self.btnMultibanco_9.setObjectName(u"btnMultibanco_9")
        self.btnMultibanco_9.setGeometry(QRect(320, 470, 31, 31))
        self.btnMultibanco_9.setFont(font2)
        self.btnMultibanco_9.setCursor(QCursor(Qt.PointingHandCursor))
        self.btnMultibanco_6 = QPushButton(form_Multibanco)
        self.btnMultibanco_6.setObjectName(u"btnMultibanco_6")
        self.btnMultibanco_6.setGeometry(QRect(320, 510, 31, 31))
        self.btnMultibanco_6.setFont(font2)
        self.btnMultibanco_6.setCursor(QCursor(Qt.PointingHandCursor))
        self.btnMultibanco_anular = QPushButton(form_Multibanco)
        self.btnMultibanco_anular.setObjectName(u"btnMultibanco_anular")
        self.btnMultibanco_anular.setGeometry(QRect(370, 470, 91, 31))
        font4 = QFont()
        font4.setPointSize(9)
        font4.setBold(True)
        self.btnMultibanco_anular.setFont(font4)
        self.btnMultibanco_anular.setCursor(QCursor(Qt.PointingHandCursor))
        self.btnMultibanco_anular.setStyleSheet(u".QPushButton {\n"
"	color: red;\n"
"}")
        self.btnMultibanco_corrigir = QPushButton(form_Multibanco)
        self.btnMultibanco_corrigir.setObjectName(u"btnMultibanco_corrigir")
        self.btnMultibanco_corrigir.setGeometry(QRect(370, 510, 91, 31))
        self.btnMultibanco_corrigir.setFont(font4)
        self.btnMultibanco_corrigir.setCursor(QCursor(Qt.PointingHandCursor))
        self.btnMultibanco_corrigir.setStyleSheet(u".QPushButton {\n"
"	color: yellow;\n"
"}")
        self.btnMultibanco_confirmar = QPushButton(form_Multibanco)
        self.btnMultibanco_confirmar.setObjectName(u"btnMultibanco_confirmar")
        self.btnMultibanco_confirmar.setGeometry(QRect(370, 550, 91, 31))
        self.btnMultibanco_confirmar.setFont(font4)
        self.btnMultibanco_confirmar.setCursor(QCursor(Qt.PointingHandCursor))
        self.btnMultibanco_confirmar.setStyleSheet(u".QPushButton {\n"
"	color: green;\n"
"}")
        self.btnMultibanco_depositos = QPushButton(form_Multibanco)
        self.btnMultibanco_depositos.setObjectName(u"btnMultibanco_depositos")
        self.btnMultibanco_depositos.setGeometry(QRect(30, 300, 51, 31))
        self.btnMultibanco_depositos.setFont(font3)
        self.btnMultibanco_depositos.setCursor(QCursor(Qt.PointingHandCursor))
        self.btnMultibanco_depositos.setIcon(icon2)
        self.btnMultibanco_depositos.setIconSize(QSize(30, 24))
        self.btnMultibanco_depositos.setCheckable(False)
        self.btnMultibanco_depositos.setAutoDefault(False)
        self.btnMultibanco_consultas = QPushButton(form_Multibanco)
        self.btnMultibanco_consultas.setObjectName(u"btnMultibanco_consultas")
        self.btnMultibanco_consultas.setGeometry(QRect(30, 240, 51, 31))
        self.btnMultibanco_consultas.setFont(font3)
        self.btnMultibanco_consultas.setCursor(QCursor(Qt.PointingHandCursor))
        self.btnMultibanco_consultas.setIcon(icon2)
        self.btnMultibanco_consultas.setIconSize(QSize(30, 24))
        self.btnMultibanco_consultas.setCheckable(False)
        self.btnMultibanco_consultas.setAutoDefault(False)
        self.btnMultibanco_levantamentos = QPushButton(form_Multibanco)
        self.btnMultibanco_levantamentos.setObjectName(u"btnMultibanco_levantamentos")
        self.btnMultibanco_levantamentos.setGeometry(QRect(30, 180, 51, 31))
        self.btnMultibanco_levantamentos.setFont(font3)
        self.btnMultibanco_levantamentos.setCursor(QCursor(Qt.PointingHandCursor))
        self.btnMultibanco_levantamentos.setIcon(icon2)
        self.btnMultibanco_levantamentos.setIconSize(QSize(30, 24))
        self.btnMultibanco_levantamentos.setCheckable(False)
        self.btnMultibanco_levantamentos.setAutoDefault(False)
        self.btnMultibanco_consultarIBAN = QPushButton(form_Multibanco)
        self.btnMultibanco_consultarIBAN.setObjectName(u"btnMultibanco_consultarIBAN")
        self.btnMultibanco_consultarIBAN.setGeometry(QRect(610, 240, 51, 31))
        self.btnMultibanco_consultarIBAN.setCursor(QCursor(Qt.PointingHandCursor))
        self.btnMultibanco_consultarIBAN.setIcon(icon1)
        self.btnMultibanco_consultarIBAN.setIconSize(QSize(30, 24))
        self.btnMultibanco_seta3 = QPushButton(form_Multibanco)
        self.btnMultibanco_seta3.setObjectName(u"btnMultibanco_seta3")
        self.btnMultibanco_seta3.setGeometry(QRect(610, 300, 51, 31))
        self.btnMultibanco_seta3.setCursor(QCursor(Qt.PointingHandCursor))
        self.btnMultibanco_seta3.setIcon(icon1)
        self.btnMultibanco_seta3.setIconSize(QSize(30, 24))
        self.btnMultibanco_codigo = QPushButton(form_Multibanco)
        self.btnMultibanco_codigo.setObjectName(u"btnMultibanco_codigo")
        self.btnMultibanco_codigo.setGeometry(QRect(610, 360, 51, 31))
        self.btnMultibanco_codigo.setCursor(QCursor(Qt.PointingHandCursor))
        self.btnMultibanco_codigo.setIcon(icon1)
        self.btnMultibanco_codigo.setIconSize(QSize(30, 24))
        self.lblMultibanco = QLabel(form_Multibanco)
        self.lblMultibanco.setObjectName(u"lblMultibanco")
        self.lblMultibanco.setEnabled(True)
        self.lblMultibanco.setGeometry(QRect(96, 61, 491, 341))
        self.lblMultibanco.setMaximumSize(QSize(491, 341))
        font5 = QFont()
        font5.setFamilies([u"Arial"])
        font5.setPointSize(22)
        font5.setBold(False)
        font5.setItalic(False)
        self.lblMultibanco.setFont(font5)
        self.lblMultibanco.setCursor(QCursor(Qt.ArrowCursor))
        self.lblMultibanco.setStyleSheet(u"QLabel{\n"
"	background-color:  #3171CE;\n"
"	font: 22pt \"Arial\";\n"
"}\n"
"")
        self.lblMultibanco.setAlignment(Qt.AlignCenter)
        self.lblMultibanco.setWordWrap(True)
        self.btnMultibanco_voltar = QPushButton(form_Multibanco)
        self.btnMultibanco_voltar.setObjectName(u"btnMultibanco_voltar")
        self.btnMultibanco_voltar.setEnabled(False)
        self.btnMultibanco_voltar.setGeometry(QRect(370, 590, 91, 31))
        font6 = QFont()
        font6.setPointSize(8)
        font6.setBold(True)
        self.btnMultibanco_voltar.setFont(font6)
        self.btnMultibanco_voltar.setCursor(QCursor(Qt.PointingHandCursor))
        self.btnMultibanco_voltar.setStyleSheet(u".QPushButton {\n"
"	color: black;\n"
"}")
        self.lblMultibanco.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.btnMultibanco_ponto.raise_()
        self.btnMultibanco_1.raise_()
        self.btnMultibanco_4.raise_()
        self.btnMultibanco_7.raise_()
        self.btnMultibanco_seta1.raise_()
        self.btnMultibanco_pagamentos.raise_()
        self.lineEdit.raise_()
        self.lineEdit_2.raise_()
        self.lineEdit_3.raise_()
        self.btnMultibanco_2.raise_()
        self.btnMultibanco_0.raise_()
        self.btnMultibanco_8.raise_()
        self.btnMultibanco_5.raise_()
        self.btnMultibanco_3.raise_()
        self.btnMultibanco_00.raise_()
        self.btnMultibanco_9.raise_()
        self.btnMultibanco_6.raise_()
        self.btnMultibanco_anular.raise_()
        self.btnMultibanco_corrigir.raise_()
        self.btnMultibanco_confirmar.raise_()
        self.btnMultibanco_depositos.raise_()
        self.btnMultibanco_consultas.raise_()
        self.btnMultibanco_levantamentos.raise_()
        self.btnMultibanco_consultarIBAN.raise_()
        self.btnMultibanco_seta3.raise_()
        self.btnMultibanco_codigo.raise_()
        self.btnMultibanco_voltar.raise_()

        self.retranslateUi(form_Multibanco)

        QMetaObject.connectSlotsByName(form_Multibanco)
    # setupUi

    def retranslateUi(self, form_Multibanco):
        form_Multibanco.setWindowTitle(QCoreApplication.translate("form_Multibanco", u"Multibanco", None))
        self.label.setText(QCoreApplication.translate("form_Multibanco", u"<html><head/><body><p align=\"center\", style=\"background-color:black\",\n"
"font-family: \"quicksand, courier new, lucida console\">\n"
"MULTIBANCO</p></body></html>", None))
        self.label_2.setText(QCoreApplication.translate("form_Multibanco", u"                                             SA\u00cdDA DE DINHEIRO", None))
        self.label_3.setText(QCoreApplication.translate("form_Multibanco", u"                   SA\u00cdDA DE TAL\u00d5ES", None))
        self.label_4.setText(QCoreApplication.translate("form_Multibanco", u"        INTRODUZA O CART\u00c3O", None))
        self.btnMultibanco_ponto.setText(QCoreApplication.translate("form_Multibanco", u".", None))
        self.btnMultibanco_1.setText(QCoreApplication.translate("form_Multibanco", u"1", None))
        self.btnMultibanco_4.setText(QCoreApplication.translate("form_Multibanco", u"4", None))
        self.btnMultibanco_7.setText(QCoreApplication.translate("form_Multibanco", u"7", None))
        self.btnMultibanco_seta1.setText("")
        self.btnMultibanco_pagamentos.setText("")
        self.btnMultibanco_2.setText(QCoreApplication.translate("form_Multibanco", u"2", None))
        self.btnMultibanco_0.setText(QCoreApplication.translate("form_Multibanco", u"0", None))
        self.btnMultibanco_8.setText(QCoreApplication.translate("form_Multibanco", u"8", None))
        self.btnMultibanco_5.setText(QCoreApplication.translate("form_Multibanco", u"5", None))
        self.btnMultibanco_3.setText(QCoreApplication.translate("form_Multibanco", u"3", None))
        self.btnMultibanco_00.setText(QCoreApplication.translate("form_Multibanco", u"00", None))
        self.btnMultibanco_9.setText(QCoreApplication.translate("form_Multibanco", u"9", None))
        self.btnMultibanco_6.setText(QCoreApplication.translate("form_Multibanco", u"6", None))
        self.btnMultibanco_anular.setText(QCoreApplication.translate("form_Multibanco", u"ANULAR", None))
        self.btnMultibanco_corrigir.setText(QCoreApplication.translate("form_Multibanco", u"CORRIGIR", None))
        self.btnMultibanco_confirmar.setText(QCoreApplication.translate("form_Multibanco", u"CONFIRMAR", None))
        self.btnMultibanco_depositos.setText("")
        self.btnMultibanco_consultas.setText("")
        self.btnMultibanco_levantamentos.setText("")
        self.btnMultibanco_consultarIBAN.setText("")
        self.btnMultibanco_seta3.setText("")
        self.btnMultibanco_codigo.setText("")
        self.lblMultibanco.setText("")
        self.btnMultibanco_voltar.setText("")
    # retranslateUi

